### ISSUE TITLE
Can't run in dev environment due to RS/Forge mismatch

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics-Compat#17]
Commit b50f1a6 updated the version of Refined Storage we pull in, and as of raoulvdberge/refinedstorage@bfaae24, it requires Forge 2694 or later or it crashes on startup. However, we're still on Forge 2655. As such, it's currently not possible to run Minecraft in this mod's dev environment. We should update our version of Forge.

**Comment by rubensworks** [comment]
Closing this in favor of https://github.com/CyclopsMC/CyclopsCore/issues/128
