### ISSUE TITLE
RS Craft Item aspect hard-coded for count of one

### ISSUE THREAD

**Issue by yurikus** [CyclopsMC/IntegratedDynamics-Compat#20]
Hi,

Was wondering why item count to craft  is hard-coded to one for RS craft task? Maybe add a `Count` property?

https://github.com/CyclopsMC/IntegratedDynamics-Compat/blob/078f3e91774257466f6fc21d21ee1229fdb0d806/src/main/java/org/cyclops/integrateddynamicscompat/modcompat/refinedstorage/aspect/RefinedStorageAspects.java#L198

**Comment by rubensworks** [comment]
Ah sure, I can easily add a property for that.

(Note that this will already be possible by default in the new Integrated Crafting mod that will be released soon...)

**Comment by yurikus** [comment]
Thank you, however does this mean that RS crafting aspect goes away?
Additionally, why curse links on most of your mods lead to a 404 page?

**Comment by rubensworks** [comment]
> does this mean that RS crafting aspect goes away?

No, no, of course not, that will remain :-)

> Additionally, why curse links on most of your mods lead to a 404 page?

Which ones?

**Comment by yurikus** [comment]
https://github.com/CyclopsMC/CommonCapabilities
- http://minecraft.curseforge.com/mc-mods/247007/files

https://github.com/CyclopsMC/IntegratedCrafting 
- https://minecraft.curseforge.com/mc-mods/287357/files

https://github.com/CyclopsMC/IntegratedTerminals
- https://minecraft.curseforge.com/mc-mods/295910/files

https://github.com/CyclopsMC/IntegratedTunnels
- https://minecraft.curseforge.com/mc-mods/251389/files

https://github.com/CyclopsMC/CapabilityProxy
- https://minecraft.curseforge.com/mc-mods/266479/files

**Comment by rubensworks** [comment]
Ah yes, those are broken because of CurseForge's recent breakage of URL strategy. I should look into fixing those at some point...
