### ISSUE TITLE
ct integration demands an "optional" output to be present

### ISSUE THREAD

**Issue by Yoghurt4C** [CyclopsMC/IntegratedDynamics-Compat#21]
trying to remove the gravel squeezing recipe with `Squeezer.removeRecipesWithOutput(<minecraft:flint>,1.0f,<minecraft:flint>,0.5f);` doesn't work in cyclopscore 1.0.5, yet it did in 1.0.4; adding a fake liquidstack like `<liquid:water>*0` doesn't remove the target recipe and `null` just flat out refuses to work

cyclopscore 1.0.5

**Comment by rubensworks** [comment]
What ID version are you using?
Can you share you Forge and CT logs?

**Comment by Yoghurt4C** [comment]
https://pastebin.com/zsV04kZy latest
https://pastebin.com/gwnUwqHq ct log
ID 1.0.7
forge 2808

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/zsV04kZy">[CHAT] ERROR: id.zs:32 > 4 methods available but §4none§r matches the paramete - Pastebin.com</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/gwnUwqHq">[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0 - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
That's weird. CT definitely seems to be recognising the correct method though:

> 
removeRecipesWithOutput(Optional ZenTypeNative: crafttweaker.item.IItemStack, Optional float, Optional ZenTypeNative: crafttweaker.item.IItemStack, Optional float, Optional ZenTypeNative: crafttweaker.liquid.ILiquidStack)

I'll play around with it to see what is going wrong. Might be a bug in CT.
