### ISSUE TITLE
ID 1.0.9 and CT

### ISSUE THREAD

**Issue by Yoghurt4C** [CyclopsMC/IntegratedDynamics-Compat#22]
https://pastebin.com/1z48E0dH
![image](https://user-images.githubusercontent.com/11313954/54725784-6fcbc380-4b81-11e9-8070-0582c7dea44a.png)

**Comment by rubensworks** [comment]
Probably the same problem as https://github.com/CyclopsMC/IntegratedDynamics/issues/708.

**Comment by rubensworks** [comment]
Will be fixed in 1.0.10
