### ISSUE TITLE
Missing sanity check

### ISSUE THREAD

**Issue by malte0811** [CyclopsMC/IntegratedDynamics-Compat#27]
https://github.com/CyclopsMC/IntegratedDynamics-Compat/blob/b0748fbe693158aea4a90f9237dd07a10718b39e/src/main/java/org/cyclops/integrateddynamicscompat/network/packet/CPacketSetSlot.java#L46-L50

As reported on ForgeCraft: this currently allows cheating in of arbitrary items, and is apparently being used "in the wild".

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Thanks for reporting!
