### ISSUE TITLE
The Issue from Reddit

### ISSUE THREAD

**Issue by Avatarded** [CyclopsMC/IntegratedDynamics-Compat#29]
#### Issue type:
I.D. appears to continue having all parts check all unique item ids every tick. 

![What_is_this_lag](https://user-images.githubusercontent.com/77522101/161752792-7a8f688b-0fa9-4166-a800-c975d17dcddf.png)

- :bug: Bug 

____

#### Short description:

This screenshot is from 1.12, but I had the same problem with 1.16, and haven't bothered to test the 1.18 version. At least, that's what I and several members of the FTB University discord think is the problem. As far as we are aware the mod never recycles unique part ids, and new parts always have a new id. Our best guess is that new parts always check every part id, to see if they're connected, even when the part that was assigned that id no longer exists (either being decommissioned in the crafting table or being otherwise destroyed). In the screenshot I had the over 1200 part ids but only about 200 active parts (not counting logic cards). 

After that point the lowest I could get it to be was about 1.3 million event subscribers at under 25 parts (including logic cards). This is what led us to the conclusion that all parts, check all unique ids, at all times.

#### Steps to reproduce the problem:

Make a bunch of parts, like, a lot a lot of parts, and put them in use.

1. ...

#### Expected behaviour:

Apparently, not certain and irrevocable world-ending lag.

____

#### Versions:

- This mod: literally every version I've played. 
- Minecraft: 1.12, and 1.16.
- Forge: IDK

It was reported first to the pack author, where I and other mods went about diagnosing the problem. Testing alone indicates that it was wholly self-contained in just the mod itself.

#### Log file:

No crash, no log.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> As far as we are aware the mod never recycles unique part ids, and new parts always have a new id. Our best guess is that new parts always check every part id, to see if they're connected, even when the part that was assigned that id no longer exists (either being decommissioned in the crafting table or being otherwise destroyed).

ID does not work like that. The unique id's are just based on an incremental counter. If you're at id 10.000.000, and only that single part is connected to the network, then only that single part will tick, the previous 99.999.999 parts will not do anything at all.

> In the screenshot I had the over 1200 part ids but only about 200 active parts (not counting logic cards).

Then you'll have 200 parts tick.

> After that point the lowest I could get it to be was about 1.3 million event subscribers at under 25 parts (including logic cards). This is what led us to the conclusion that all parts, check all unique ids, at all times.

How did you detect this? It's not visible on your screenshot AFAICS.

> Make a bunch of parts, like, a lot a lot of parts, and put them in use.

Unfortunately, that's not really enough to help me reproduce the problem. If there's a world you could share with only ID mods, that would definitely help out a lot in uncovering the problem you are experiencing.

> This mod: literally every version I've played.

The mod has evolved _a lot_ over the several years it has existed (including performance-wise), so I would suggest trying again with the latest version.

**Comment by Avatarded** [comment]
I forgot to mention this was on a single player world. Other players have told me that the problems on servers are more... pronounced. And, the unique part ids accrue much more quickly.

**Comment by Avatarded** [comment]
> > In the screenshot I had the over 1200 part ids but only about 200 active parts (not counting logic cards).
> 
> Then you'll have 200 parts tick.

But I don't have that. I have over 6.66 million event subscribers from ID.

> How did you detect this? It's not visible on your screenshot AFAICS.

As stated in the top left of the screenshot this report was compiled by Lag Goggles ([Cursefore Link](https://www.curseforge.com/minecraft/mc-mods/laggoggles)). There's other lag detecting mods we used in 1.16 but I don't remember it's name. People running servers used the server tools but I don't have access to their data.

> Unfortunately, that's not really enough to help me reproduce the problem. If there's a world you could share with only ID mods, that would definitely help out a lot in uncovering the problem you are experiencing.

I was using the parts to do everything. Basic logistics like item & energy transfer, sorting, filtering, etc. I was also experimenting with logic operations. Just the basic utility of the mod exactly as the mod's included directory/quest book indicated.
 
> The mod has evolved _a lot_ over the several years it has existed (including performance-wise), so I would suggest trying again with the latest version.

I don't use ID as a stand-alone mod and I can currently find no mod packs for 1.18 that feature the mod.

**Comment by rubensworks** [comment]
> We used Lag Goggles ([Cursefore Link](https://www.curseforge.com/minecraft/mc-mods/laggoggles)).

Perhaps it was a bug in that mod then? Because ID registers only a constant number of event subscribers. All parts tick in a single event subscriber. So adding new parts will not increase the number of event subscribers.

> I was using the parts to do everything. Basic logistics like item & energy transfer, sorting, filtering, etc. I was also experimenting with logic operations. Just the basic utility of the mod exactly as the mod's included directory/quest book indicated.

There's a countably infinite number of things you could do with this mod. "just do everything" unfortunately doesn't give me enough details to reproduce the problem.

I'm afraid there's not much we can do with this issue then at this point.
If you (or anyone else) has additional information to give related to a large number of event subscribers, please share it here and I'll happily reopen this issue.

-----

Side-note: pre-1.16 versions of ID had the network diagnostics feature (I haven't had the time yet to restore it for 1.16+ yet). This allows you to view the tick times of each part separately. This could then be used to discover parts that have an excessive tick time, which could by caused by inefficient operator chains, interaction with slow TEs, ...

**Comment by Avatarded** [comment]
> Perhaps it was a bug in that mod then? Because ID registers only a constant number of event subscribers. All parts tick in a single event subscriber. So adding new parts will not increase the number of event subscribers.

It wasn't just lag goggles. We also checked server files and used other mods to verify the results. I don't have access to the server data since it was run by someone else. Since more than a few players used more than a few methods of verification the problem is definitely with _your_ mod.
 

> There's a countably infinite number of things you could do with this mod. "just do everything" unfortunately doesn't give me enough details to reproduce the problem.

Countably infinite is any set with a size equal to that of the integers, where a mapping from integers to that set is one to one. There is not a countably infinite number of things you can make or do in minecraft. There is a finite number of things you can do. You can just do those same finite things an infinite number of times. Your own mod is not infinite in scope, either, as it has a finite list of options it adds to the game.

> Side-note: pre-1.16 versions of ID had the network diagnostics feature (I haven't had the time yet to restore it for 1.16+ yet). This allows you to view the tick times of each part separately. This could then be used to discover parts that have an excessive tick time, which could by caused by inefficient operator chains, interaction with slow TEs, ...

If you want meaningful diagnostics to problems then you should prioritize bringing this tool back into the game. The fact that you have neglected it, while prioritizing updating the mod to a version nobody's actually playing modded yet, speaks poorly of you. It says you care more about getting attention for your mod than ensuring your mod provides a good experience to users by virtue of not allowing them to (help you) diagnose the problems they're having when they don't have a good experience.

**Comment by rubensworks** [comment]
It seems you are clearly superior over me as developer of a logic mod like ID, so perhaps it's better for you to stop using this mod and create a much better one yourself.

In the meantime, I'll just continue with my selfish attention-grabbing.

-----

But for real; comments like these really suck out the motivation of mod developers. I hope you think twice in the future before placing such hurtful comments.
