### ISSUE TITLE
Can't run in dev without disabling most mods

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics-Compat#4]
You can't currently run IntegratedDynamics-Compat in the development environment without disabling almost all of the mods. If you try, your game will crash with a NoSuchFieldError or NoSuchMethodError. This is because of changes to the MCP mappings. For example, Tinkers' Construct contains several references to "isBlockContainer", but this was changed in more recent mappings to be "hasTileEntity". In a normal environment, these would both be the same SRG name in the compiled classes, but in the development environment they're not, resulting in this problem. This can't be easily fixed by changing the version of the mappings we use; doing that will only result in it crashing somewhere else.

**Comment by rubensworks** [comment]
Yes, ForgeGradle's deobfuscation doesn't always work that well.

We'll have to update all dependencies to the latest 1.12.2 versions and *hope* they are using the latest MCP versions.

**Comment by rubensworks** [comment]
@josephcsible Is this something you are looking into as part of #5?

**Comment by josephcsible** [comment]
I just worked around it for #5 by temporarily disabling all of the compats except for RFTools. I'm not aware of a way to actually fix this ourselves right now, because many of these mods are still using old mappings even in their newest versions.

**Comment by rubensworks** [comment]
`deobfCompile` should fix most cases. But forgegradle's built-in decompiler sometimes misses some things, so there _may_ be some issues with that, but probably not.

**Comment by rubensworks** [comment]
~~Also, it has to be fixed in any case for next release, otherwise the compats can't be built.~~

Edit: Nvm this comment, it's late.
